name: EmmaRogers
favicon: null
layout_spectrum: 0.17917
typography_spectrum: 0.301704520592466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#909f9c'
    - '#fefefe'
    - '#556765'
    - '#323004'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
