name: EmmaRogers
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#909f9c'
    - '#fefefe'
    - '#556765'
    - '#323004'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
